Add auth token
genexuslabs/gxserver-client pull request #14
Opened 2022-03-25 14:45 UTC by agutierrezgx

userName and userPassword values for ServiceData instance cannot be empty because that causes soap security exception

2022-03-28 18:48 UTC, jlamasrios commented
Actualicé el branch desde main para que ejecutara los tests en {java 8, java11} x {windows, ubuntu} y falla con Java8 por el uso de string.isBlank() que está solo en Java11

2022-03-28 19:04 UTC, jlamasrios requested changes

2022-03-28 19:04 UTC, jlamasrios commented on src/test/java/com/genexus/gxserver/client/clients/TeamWorkService2ClientTest.java
> +    public void testGetRevisionsUsingToken() throws Exception {
Si no entendí mal, este método es igual al testGetRevisions() y solo cambia la autenticación, verdad? Convendría que la parte común estuviera en un método que llamen los dos en lugar de estar repetido.

Esto en particular me lo quedo yo para corregir porque además al hacer el merge de los cambios que faltaban actualizar desde main me parece que hay cosas que no quedaron del todo bien.

2022-03-28 19:40 UTC, jlamasrios commented on src/test/java/com/genexus/gxserver/client/clients/TeamWorkService2ClientTest.java
> +    public void testGetRevisionsUsingToken() throws Exception {
Hice commit [921dcae](https://github.com/genexuslabs/gxserver-client/pull/14/commits/921dcae1d629f0ac05afef8062cf0962c848258a) para resolver esto.

2022-03-28 20:01 UTC, jlamasrios commented on src/main/java/com/genexus/gxserver/client/clients/common/ServiceData.java
> +        this.userName = "usr";
Hmm... now I see your comment at the PR start, and I think @fedeazzato had also personally commented about this with me some days ago. Sorry! Resolving this conversation.

2022-03-28 23:32 UTC, agutierrezgx commented on src/test/java/com/genexus/gxserver/client/clients/ServerData.java
> +                    "https://open.genexusserver.com/v17",
Empezaron a fallar un par de assert en el test de getRevisions. Al principio pense que fue producto de mis cambios, pero no. Al cambiar de server magicamente se arreglo, asi que sospecho que debe haber alguna KB con algo raro en el samples. Me lo quedo para revisar porque esta raro

2022-03-28 23:35 UTC, agutierrezgx commented on src/test/java/com/genexus/gxserver/client/clients/ServerData.java
> +                    "a9b30c7d-888a-45fa-9493-3f9aaadedae0!e874ed2c1dc477876adf73a2e7083ce9fc47441afcb38005315c6013dcccc79c06a320b1dbb2f4"
Es mio. Entre el cambio de server y probar otras cosas quedo el token ahi. Lo cambio.

2022-03-28 23:40 UTC, agutierrezgx commented on src/test/java/com/genexus/gxserver/client/clients/ServerData.java
> +                    "https://open.genexusserver.com/v17",
Ta, fue porque no estaba al dia con los commits de la main. Hoy nos reunimos con Jose Echague por el tema de las actions y publicar en Maven y me habia comentado eso mismo. Perdon!
En ese caso podemos volver a usar el samples sin problemas

2022-03-29 13:09 UTC, agutierrezgx commented
Quedaron los cambios para usar la variable de ambiente en lugar de el token explicito y lo del isBlank, pero parece que no tengo permiso para definir el secret.

2022-03-29 16:10 UTC, jlamasrios commented on src/test/java/com/genexus/gxserver/client/clients/ServerData.java
> +                    "https://open.genexusserver.com/v17",
Todo bien. Hice el cambio para volver a usar el de samples

2022-03-29 21:03 UTC, jlamasrios approved these changes

2022-03-29 21:05 UTC, jlamasrios commented
> Quedaron los cambios para usar la variable de ambiente en lugar de el token explicito y lo del isBlank, pero parece que no tengo permiso para definir el secret.

Buenísimo. Agregué el secret, te puse como admin del repo para que para otra vuelta lo puedas hacer derecho y modifiqué el workflow de integration para que cargue el token del secret a la variable de ambiente.

2022-03-29 21:07 UTC, merged